version: '3'

volumes:
  elasticsearch_data: {}
  files_data: {}

services:
  server:
    build:
      context: ./server
      dockerfile: ../compose/server/Dockerfile
    environment:
      FLASK_APP: app
      FLASK_ENV: production
      FLASK_DEBUG: 0
      ES_URL: http://elasticsearch:9200
    command: /app/start
    ports:
      - "5001:5001"
    depends_on:
      elasticsearch:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - files_data:/app/files
    restart: unless-stopped

    networks:
      - ocr-network

  celery_worker:
    build:
      context: ./server
      dockerfile: ../compose/server/Dockerfile
    environment:
      CELERY_BROKER_URL: redis://redis:6379
      CELERY_RESULT_BACKEND: redis://redis:6379
      C_FORCE_ROOT: true
    command: celery -A celery_app.celery worker --loglevel=info --without-gossip --without-mingle --without-heartbeat -Ofair --concurrency=8 -P prefork
    volumes:
      - files_data:/app/files
    depends_on:
      - redis
    restart: unless-stopped

    networks:
      - ocr-network

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 15
      start_period: 10s
    volumes:
      - files_data:/app/files
    restart: unless-stopped

    networks:
      - ocr-network

  nginx:
    build:
      context: .
      dockerfile: ./compose/nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - server
    volumes:
      - files_data:/usr/share/nginx/html/files
    environment:
      PUBLIC_URL: /ocr/
      REACT_APP_API_URL: ./api/
    restart: unless-stopped

    networks:
      - ocr-network

  elasticsearch:
    build:
      context: ./compose/elasticsearch
      dockerfile: Dockerfile
    ports:
     - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    environment:
      xpack.security.enabled: false
      discovery.type: single-node
    healthcheck:
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:9200
      interval: 10s
      timeout: 30s
      retries: 15
      start_period: 10s
    restart: unless-stopped

    networks:
      - ocr-network

networks:
  ocr-network:
    driver: bridge